###eureka 服务端口号
server:
  port: 8502
spring:
  application:
    name: consul-member
#spring.dubbo.registry.address=zookeeper://127.0.0.1:2181
#spring.dubbo.protocol.name=dubbo
#spring.dubbo.protocol.port=20880
#spring.dubbo.scan=org.spring.springboot.dubbo
  dubbo: 
    registry: 
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.itmayiedu.api.member     