###服务端口号
server:
  port: 8000
###服务名称
spring: 
 dubbo: 
    application: 
      name: dubbo-member
    registry: 
      address: zookeeper://127.0.0.1:2181
    protocol: 
      name: dubbo
      port: 20880
    scan: com.itmayiedu.api.member.impl
 application:
    name: dubbo_member
      
